
export ZSH="$HOME/.oh-my-zsh"

export GCLOUD_DEFAULT_ACCOUNT="jonathan.norton@shopify.com"
export GCLOUD_DEFAULT_PROJECT="sdp-stg-financial-services"
export GCLOUD_DEFAULT_PROD_PROJECT="sdp-prd-financial-services"
export SHOPIFY_AI_API_ENDPOINT="https://proxy.shopify.ai/v1"
export SHOPIFY_AI_API_KEY="shopify-eyJpZCI6Ijg2YmEzMzZhMDNkZjNlNDBlYWNiYjIyYWJkNTMwM2JhIiwibW9kZSI6InBlcnNvbmFsIiwiZW1haWwiOiJqb25hdGhhbi5ub3J0b25Ac2hvcGlmeS5jb20iLCJleHBpcnkiOjE3Njg4NTU3OTh9-gmTza5UHcvBEP2wqE3A5skoR+tBccAe3Gr8Kcoq4gvE="
export SHOPIFY_AI_API_MODEL="anthropic:claude-opus-4-5-20251101"


# Define your Vertex AI Workbench instances and their locations
typeset -A WB_INSTANCES
WB_INSTANCES=(
  jndev "us-west1-a"
  jn1 "us-west1-a"
  jn2 "us-west1-a"
  jvjn-ml-1 "us-central1-a"
  jvjn-ml-2 "us-central1-a"
  jvjn-ml-3 "us-central1-a"
  jvjn-ml-4 "us-central1-a"
  jvjn-ml-5 "us-central1-a"
  jvjn-ml-6 "us-central1-a"
  jvjn-ml-7 "us-central1-a"
  ec-ml-4-gpu "us-west1-a"
)

plugins=(git gcloud macos sublime gcloud-vertex-workbench)

source $ZSH/oh-my-zsh.sh

# Homebrew (should come FIRST)
eval "$(/opt/homebrew/bin/brew shellenv)"

# tec profile (should come AFTER Homebrew)
[[ -x /Users/jn/.local/state/tec/profiles/base/current/global/init ]] && eval "$(/Users/jn/.local/state/tec/profiles/base/current/global/init zsh)"

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

# Created by `pipx` on 2026-01-18 22:46:25
export PATH="$PATH:/Users/jn/.local/bin"
